# Generated by Django 3.1.7 on 2022-04-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220401_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', help_text='Upload a product image', upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
