# Generated by Django 3.1.7 on 2022-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.IntegerField(default=0, help_text='format: required, default-0', verbose_name='units/qty of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.IntegerField(default=0, help_text='format: required, default-0', verbose_name='units sold to date'),
        ),
    ]
