# Generated by Django 3.1.7 on 2022-04-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviewvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='format: required, max-255', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.IntegerField(default=0, help_text='format: required, default-0', verbose_name='units'),
        ),
    ]
