# Generated by Django 3.1.7 on 2022-05-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220406_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='format: not required, max-1000', max_length=1000, verbose_name='category description'),
        ),
    ]
